-- Migrate LAUNDRY_STATUS to a single-row "laundry" record.
DELETE FROM LAUNDRY_STATUS;

ALTER TABLE LAUNDRY_STATUS DROP CONSTRAINT LAUNDRY_STATUS_MACHINE_TYPE_CK;
ALTER TABLE LAUNDRY_STATUS ADD CONSTRAINT LAUNDRY_STATUS_MACHINE_TYPE_CK CHECK (
  MACHINE_TYPE IN ('laundry')
);

INSERT INTO LAUNDRY_STATUS (
  MACHINE_TYPE,
  STATUS,
  NOTES
) VALUES ('laundry', 'available', 'Seeded single laundry status.');

-- Keep history flexible to preserve existing records.
ALTER TABLE LAUNDRY_STATUS_HISTORY DROP CONSTRAINT LAUNDRY_STATUS_HIST_MACHINE_CK;
ALTER TABLE LAUNDRY_STATUS_HISTORY ADD CONSTRAINT LAUNDRY_STATUS_HIST_MACHINE_CK CHECK (
  MACHINE_TYPE IN ('laundry', 'washer', 'dryer')
);
